android.useAndroidX=true
qtGradlePluginType=com.android.application
androidPackageName=app.status.mobile
androidBuildToolsVersion=36.0.0
androidCompileSdkVersion=android-36
androidNdkVersion=27.2.12479018
qtAndroidDir=/opt/qt/6.11.0/android_arm64_v8a/src/android/java
qtMinSdkVersion=28
qtTargetSdkVersion=36
qtTargetAbiList=arm64-v8a
org.gradle.jvmargs=-Xmx8704M -XX:+UseParallelGC
